USE [master]
GO
/****** Object:  Database [ForoWorldSkill]    Script Date: 28/07/2021 10:59:57 ******/
CREATE DATABASE [ForoWorldSkill]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ForoWorldSkill', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ForoWorldSkill.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ForoWorldSkill_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ForoWorldSkill_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ForoWorldSkill] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ForoWorldSkill].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ForoWorldSkill] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET ARITHABORT OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ForoWorldSkill] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ForoWorldSkill] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ForoWorldSkill] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ForoWorldSkill] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ForoWorldSkill] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ForoWorldSkill] SET  MULTI_USER 
GO
ALTER DATABASE [ForoWorldSkill] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ForoWorldSkill] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ForoWorldSkill] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ForoWorldSkill] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ForoWorldSkill] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ForoWorldSkill] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ForoWorldSkill] SET QUERY_STORE = OFF
GO
USE [ForoWorldSkill]
GO
/****** Object:  Table [dbo].[Comentario]    Script Date: 28/07/2021 10:59:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comentario](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ComentarioTexto] [varchar](300) NULL,
	[UsuarioID] [int] NULL,
	[TemaID] [int] NULL,
	[Fecha] [datetime] NULL,
 CONSTRAINT [PK_Comentario] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rol]    Script Date: 28/07/2021 10:59:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rol](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NULL,
 CONSTRAINT [PK_Rol] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tema]    Script Date: 28/07/2021 10:59:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tema](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Titulo] [varchar](1000) NOT NULL,
	[Descripcion] [text] NULL,
	[AdministradorID] [int] NULL,
	[Fecha] [datetime] NULL,
 CONSTRAINT [PK_Tema] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 28/07/2021 10:59:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Correo] [varchar](200) NOT NULL,
	[Contraseña] [varchar](200) NOT NULL,
	[RolID] [int] NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Rol] ON 
GO
INSERT [dbo].[Rol] ([ID], [Nombre]) VALUES (1, N'Administrador')
GO
INSERT [dbo].[Rol] ([ID], [Nombre]) VALUES (2, N'Visitante')
GO
SET IDENTITY_INSERT [dbo].[Rol] OFF
GO
SET IDENTITY_INSERT [dbo].[Usuario] ON 
GO
INSERT [dbo].[Usuario] ([ID], [Nombre], [Correo], [Contraseña], [RolID]) VALUES (1, N'Administrador', N'administrador@gmail.com', N'admin123', 1)
GO
SET IDENTITY_INSERT [dbo].[Usuario] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Usuario]    Script Date: 28/07/2021 10:59:57 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Usuario] ON [dbo].[Usuario]
(
	[Correo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Comentario]  WITH CHECK ADD  CONSTRAINT [FK_Comentario_Tema] FOREIGN KEY([TemaID])
REFERENCES [dbo].[Tema] ([ID])
GO
ALTER TABLE [dbo].[Comentario] CHECK CONSTRAINT [FK_Comentario_Tema]
GO
ALTER TABLE [dbo].[Comentario]  WITH CHECK ADD  CONSTRAINT [FK_Comentario_Usuario] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuario] ([ID])
GO
ALTER TABLE [dbo].[Comentario] CHECK CONSTRAINT [FK_Comentario_Usuario]
GO
ALTER TABLE [dbo].[Tema]  WITH CHECK ADD  CONSTRAINT [FK_Tema_Usuario] FOREIGN KEY([AdministradorID])
REFERENCES [dbo].[Usuario] ([ID])
GO
ALTER TABLE [dbo].[Tema] CHECK CONSTRAINT [FK_Tema_Usuario]
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_Rol] FOREIGN KEY([RolID])
REFERENCES [dbo].[Rol] ([ID])
GO
ALTER TABLE [dbo].[Usuario] CHECK CONSTRAINT [FK_Usuario_Rol]
GO
USE [master]
GO
ALTER DATABASE [ForoWorldSkill] SET  READ_WRITE 
GO
